
TARGET=containersTest


#############################
CPPFLAGS = -Wall -Wconversion -pedantic -ansi -Werror -g
LDFLAGS=
CC=g++

.PHONEY:clean

$(TARGET):container.h array.h dlist.h

clean:
	rm -f $(TARGET)

#############################


