SRC=DLinkListTest.c DLinkList.c
#Alexander Timoshenko
FLAGS = -Wall -Wconversion -pedantic -ansi -Werror -g
#FLAGS = -Wall -Wconversion -pedantic -ansi -Werror -g




#test.out : $(SRC) DLinkList.h ../ADTErr.h ../mu_test.h
test.out: $(SRC)
	gcc	$(FLAGS) $(SRC) -o test.out



