
TARGET=citiesTest


#############################
CPPFLAGS = -Wall -Wconversion -pedantic -ansi -Werror -g
LDFLAGS=
CC=g++

.PHONEY:clean

$(TARGET):# building_t.h street_t.h city_t.h

clean:
	rm -f $(TARGET)

#############################


