
#Alexander Timoshenko

FLAGS = -Wall -Wconversion -pedantic -ansi -Werror 
#FLAGS = -Wall -Wconversion -pedantic -ansi -Werror -g
SRC = DLinkListTest.c DLinkList.c

#INC = DLinkList.h

test.out : $(SRC) DLinkList.h
	gcc $(FLAGS) $(SRC) -o test.out



